import { Router, type IRouter } from "express";
import healthRouter from "./health";
import songRouter from "./generate/song";
import songsRouter from "./songs";
import videoRouter from "./generate/video";
import songVideoRouter from "./generate/song-video";
import autoVideoPlanRouter from "./generate/auto-video-plan";
import promoRouter from "./generate/promo";
import thumbnailRouter from "./generate/thumbnail";
import projectsRouter from "./projects";
import artistVaultsRouter from "./artist-vaults";
import artistVoicesRouter from "./artist-voices";
import locationsRouter from "./locations";
import artistOutfitsRouter from "./artist-outfits";
import waitlistRouter from "./waitlist";
import contactRouter from "./contact";
import transcribeRouter from "./transcribe";
import analyzeSectionsRouter from "./analyze-sections";
import demoClipRouter from "./generate/demo-clip";
import runwayClipRouter from "./generate/runway-clip";
import artistImageRouter from "./generate/artist-image";
import uploadClipRouter from "./generate/upload-clip";
import adminRouter from "./admin";
import exportVideoRouter from "./generate/export-video";
import prepareExportFilesRouter from "./generate/prepare-export-files";
import exportDoctorRouter from "./generate/export-doctor";
import improvePromptRouter from "./generate/improve-prompt";
import autoEditRouter from "./generate/auto-edit";
import aiEditPlanRouter from "./generate/ai-edit-plan";
import mixPlanRouter from "./generate/mix-plan";
import musicAudioRouter from "./generate/music-audio";
import musicExportRouter from "./music-export";
import uploadWatermarkRouter from "./upload-watermark";
import devRouter from "./dev";
import stripePaymentsRouter from "./stripe-payments";
import creditsRouter from "./credits";
import generatedClipsRouter from "./generated-clips";
import draftsRouter from "./drafts";
import generationHistoryRouter from "./generation-history";
import thumbnailsRouter from "./thumbnails";
import lipSyncRouter from "./lip-sync";
import chatRouter from "./chat";
import preProductionRouter from "./generate/pre-production";
import randomizerRouter from "./generate/randomizer";
import hookStudioRouter from "./generate/hook-studio";
import monetizationCoachRouter from "./generate/monetization-coach";
import academyRouter from "./generate/academy";
import commentRepliesRouter from "./generate/comment-replies";
import contentCalendarRouter from "./generate/content-calendar";
import upscaleRouter from "./generate/upscale";
import streamPackRouter from "./generate/stream-pack";
import watermarkRemovalRouter from "./generate/watermark-removal";
import logoRouter from "./generate/logo";
import emailListRouter from "./generate/email-list";
import introOutroRouter from "./generate/intro-outro";
import llcGuideRouter from "./generate/llc-guide";
import socialRouter from "./social";
import discordRouter from "./discord";
import jobNotificationsRouter from "./job-notifications";

const router: IRouter = Router();

router.use(healthRouter);
router.use(songRouter);
router.use(videoRouter);
router.use(songVideoRouter);
router.use(autoVideoPlanRouter);
router.use(promoRouter);
router.use(thumbnailRouter);
router.use(projectsRouter);
router.use(artistVaultsRouter);
router.use(artistVoicesRouter);
router.use(locationsRouter);
router.use(artistOutfitsRouter);
router.use(songsRouter);
router.use(waitlistRouter);
router.use(contactRouter);
router.use(transcribeRouter);
router.use(analyzeSectionsRouter);
router.use(demoClipRouter);
router.use(runwayClipRouter);
router.use(artistImageRouter);
router.use(uploadClipRouter);
router.use(adminRouter);
router.use(exportVideoRouter);
router.use(prepareExportFilesRouter);
router.use(exportDoctorRouter);
router.use(improvePromptRouter);
router.use(autoEditRouter);
router.use(aiEditPlanRouter);
router.use(mixPlanRouter);
router.use(musicAudioRouter);
router.use(musicExportRouter);
router.use(uploadWatermarkRouter);
router.use(devRouter);
router.use(stripePaymentsRouter);
router.use(creditsRouter);
router.use(generatedClipsRouter);
router.use(draftsRouter);
router.use(generationHistoryRouter);
router.use(thumbnailsRouter);
router.use(lipSyncRouter);
router.use(preProductionRouter);
router.use(chatRouter);
router.use(randomizerRouter);
router.use(hookStudioRouter);
router.use(monetizationCoachRouter);
router.use(academyRouter);
router.use(commentRepliesRouter);
router.use(contentCalendarRouter);
router.use(upscaleRouter);
router.use(watermarkRemovalRouter);
router.use(streamPackRouter);
router.use(logoRouter);
router.use(emailListRouter);
router.use(introOutroRouter);
router.use(llcGuideRouter);
router.use(socialRouter);
router.use(discordRouter);
router.use(jobNotificationsRouter);

export default router;
