import { Router, type IRouter } from "express";
import healthRouter from "./health";
import songRouter from "./generate/song";
import songsRouter from "./songs";
import playlistRouter from "./playlist";
import videoRouter from "./generate/video";
import songVideoRouter from "./generate/song-video";
import autoVideoPlanRouter from "./generate/auto-video-plan";
import promoRouter from "./generate/promo";
import thumbnailRouter from "./generate/thumbnail";
import projectsRouter from "./projects";
import hubProjectsRouter from "./hub-projects";
import reviewLinksRouter from "./review-links";
import artistVaultsRouter from "./artist-vaults";
import generationsRouter from "./generations";
import artistVoicesRouter from "./artist-voices";
import locationsRouter from "./locations";
import artistOutfitsRouter from "./artist-outfits";
import waitlistRouter from "./waitlist";
import contactRouter from "./contact";
import spotlightRouter from "./spotlight";
import transcribeRouter from "./transcribe";
import analyzeSectionsRouter from "./analyze-sections";
import demoClipRouter from "./generate/demo-clip";
import runwayClipRouter from "./generate/runway-clip";
import artistImageRouter from "./generate/artist-image";
import uploadClipRouter from "./generate/upload-clip";
import adminRouter from "./admin";
import bowChallengeRouter from "./bow-challenge";
import nfcCardsRouter from "./nfc-cards";
import jewelryOrdersRouter from "./jewelry";
import exportVideoRouter from "./generate/export-video";
import prepareExportFilesRouter from "./generate/prepare-export-files";
import exportDoctorRouter from "./generate/export-doctor";
import improvePromptRouter from "./generate/improve-prompt";
import autoEditRouter from "./generate/auto-edit";
import aiEditPlanRouter from "./generate/ai-edit-plan";
import mixPlanRouter from "./generate/mix-plan";
import musicAudioRouter from "./generate/music-audio";
import beatRouter from "./generate/beat";
import musicExportRouter from "./music-export";
import uploadWatermarkRouter from "./upload-watermark";
import devRouter from "./dev";
import stripePaymentsRouter from "./stripe-payments";
import creditsRouter from "./credits";
import bonusRouter from "./bonus";
import teamsRouter from "./teams";
import referralsRouter from "./referrals";
import generatedClipsRouter from "./generated-clips";
import draftsRouter from "./drafts";
import generationHistoryRouter from "./generation-history";
import thumbnailsRouter from "./thumbnails";
import showcaseRouter from "./showcase";
import lipSyncRouter from "./lip-sync";
import chatRouter from "./chat";
import freeChatRouter from "./free-chat";
import preProductionRouter from "./generate/pre-production";
import randomizerRouter from "./generate/randomizer";
import hookStudioRouter from "./generate/hook-studio";
import ctaGeneratorRouter from "./generate/cta-generator";
import gamersRouter from "./generate/gamers";
import proToolsAiRouter from "./generate/pro-tools-ai";
import soundFinderRouter from "./generate/sound-finder";
import monetizationCoachRouter from "./generate/monetization-coach";
import brandCalculatorRouter from "./generate/brand-calculator";
import academyRouter from "./generate/academy";
import commentRepliesRouter from "./generate/comment-replies";
import contentCalendarRouter from "./generate/content-calendar";
import tipJarRouter from "./generate/tip-jar";import interviewPrepRouter from "./generate/interview-prep";import upscaleRouter from "./generate/upscale";
import titleStudioRouter from "./generate/title-studio";
import sponsorsRouter from "./generate/sponsors";
import brandingShopRouter from "./generate/branding-shop";
import collabsRouter from "./generate/collabs";
import communityRouter from "./generate/community";
import contestsRouter from "./generate/contests";
import copyrightRouter from "./generate/copyright";
import coverArtRouter from "./generate/cover-art";
import emailListRouter from "./generate/email-list";
import liveShoppingRouter from "./live-shopping";
import membershipsRouter from "./generate/memberships";
import podcastRouter from "./generate/podcast";
import pressKitRouter from "./generate/press-kit";
import pressReleaseRouter from "./generate/press-release";
import royaltiesRouter from "./generate/royalties";
import scriptWriterRouter from "./generate/script-writer";
import sfxRouter from "./generate/sfx";
import thumbnailTestRouter from "./generate/thumbnail-test";
import trendPredictorRouter from "./generate/trend-predictor";
import voiceoverRouter from "./generate/voiceover";
import beatsRouter from "./generate/beats";
import captionStylerRouter from "./generate/caption-styler";
import lyricVideoRouter from "./generate/lyric-video";
import backgroundRemovalRouter from "./generate/background-removal";
import videoBackgroundRemovalRouter from "./generate/video-background-removal";
import bgReplacerRouter from "./generate/bg-replacer";
import lyricsGeneratorRouter from "./generate/lyrics-generator";
import autoReframeRouter from "./generate/auto-reframe";
import voiceEffectsRouter from "./generate/voice-effects";
import audioDuckingRouter from "./generate/audio-ducking";
import videoStylesRouter from "./generate/video-styles";
import silenceRemovalRouter from "./generate/silence-removal";
import logoAnimatorRouter from "./generate/logo-animator";
import transitionsRouter from "./generate/transitions";
import videoTemplateRouter from "./generate/video-template";
import smartClipsRouter from "./generate/video-to-shorts";
import voicePersonasRouter from "./generate/voice-personas";
import voiceCloneRouter from "./generate/voice-clone";
import scriptToVideoRouter from "./generate/script-to-video";
import socialSchedulerRouter from "./generate/scheduler";
import bgMusicRouter from "./generate/bg-music";
import translateCaptionsRouter from "./generate/translate-captions";
import socialAnalyticsRouter from "./generate/social-analytics";
import hookAnalyzerRouter from "./generate/hook-analyzer";
import showNotesRouter from "./generate/show-notes";
import autoChaptersRouter from "./generate/auto-chapters";
import chaptersRouter from "./generate/chapters";
import voiceoverProRouter from "./generate/voiceover-pro";
import brandKitRouter from "./generate/brand-kit";
import brollSuggesterRouter from "./generate/broll-suggester";
import colorGradeRouter from "./generate/color-grade";
import speedPresetsRouter from "./generate/speed-presets";
import videoTrimRouter from "./generate/video-trim";
import slowMotionRouter from "./generate/slow-motion";
import loopMakerRouter from "./generate/loop-maker";
import endScreenRouter from "./generate/end-screen";
import videoMergerRouter from "./generate/video-merger";
import beatSyncRouter from "./generate/beat-sync";
import thumbnailAbRouter from "./generate/thumbnail-ab";
import thumbBgRouter from "./generate/thumb-bg";
import chapterArtRouter from "./generate/chapter-art";
import socialKitRouter from "./generate/social-kit";
import storyboardRouter from "./generate/storyboard";
import volumeNormRouter from "./generate/volume-norm";
import stabilizeRouter from "./generate/stabilize";
import motionTrackRouter from "./generate/motion-track";
import videoTitlesRouter from "./generate/video-titles";
import clipDescriptionsRouter from "./generate/clip-descriptions";
import descAbTestRouter from "./generate/desc-ab-test";
import seoScoreRouter from "./generate/seo-score";
import thumbnailTextRouter from "./generate/thumbnail-text";
import audiogramRouter from "./generate/audiogram";
import memeGeneratorRouter from "./generate/meme-generator";
import testimonialRouter from "./generate/testimonial";
import nicheAnalyzerRouter from "./generate/niche-analyzer";
import ideaValidatorRouter from "./generate/idea-validator";
import hashtagsRouter from "./generate/hashtags";
import virtualBgRouter from "./generate/virtual-bg";
import masteringRouter from "./generate/mastering";
import bioGeneratorRouter from "./generate/bio-generator";
import communityPostRouter from "./generate/community-post";
import repurposeRouter from "./generate/repurpose";
import samplePackRouter from "./generate/sample-pack";
import stemSplitterRouter from "./generate/stem-splitter";
import streamerClipsRouter from "./generate/streamer-clips";
import videoTranslatorRouter from "./generate/video-translator";
import vocalRemovalRouter from "./generate/vocal-removal";
import streamPackRouter from "./generate/stream-pack";
import watermarkRemovalRouter from "./generate/watermark-removal";
import mediaImporterRouter from "./generate/media-importer";
import logoRouter from "./generate/logo";
import introOutroRouter from "./generate/intro-outro";
import introOutroFfmpegRouter from "./generate/intro-outro-ffmpeg";
import viralityCheckRouter from "./generate/virality-check";
import upscaleImageRouter from "./generate/upscale-image";
import analyticsHubRouter from "./generate/analytics-hub";
import competitorTrackerRouter from "./generate/competitor-tracker";
import contentPlansRouter from "./content-plans";
import llcGuideRouter from "./generate/llc-guide";
import tourPlannerRouter from "./generate/tour-planner";
import setlistRouter from "./generate/setlist";
import promoGeneratorRouter from "./generate/promo-generator";
import socialRouter from "./social";
import analyticsRouter from "./analytics";
import discordRouter from "./discord";
import discordBotRouter from "./discord-bot";
import jobNotificationsRouter from "./job-notifications";
import distributionRouter from "./generate/distribution";
import schedulerRouter from "./scheduler";
import merchRouter from "./generate/merch";
import jewelryRouter from "./generate/jewelry";
import playlistPitchRouter from "./generate/playlist-pitch";
import labelPitchRouter from "./generate/label-pitch";
import channelAuditRouter from "./generate/channel-audit";
import contractAnalyzerRouter from "./generate/contract-analyzer";
import moviesRouter from "./generate/movies";
import websiteBuilderRouter from "./generate/website-builder";
import mediaDetectorRouter from "./generate/media-detector";
import sponsorshipOutreachRouter from "./generate/sponsorship-outreach";
import sponsorReadRouter from "./generate/sponsor-read";
import shoutoutsRouter from "./generate/shoutouts";
import releaseChecklistRouter from "./generate/release-checklist";
import thumbnailGeneratorRouter from "./generate/thumbnail-generator";
import audioCleanupRouter from "./generate/audio-cleanup";
import aspectConvertRouter from "./generate/aspect-convert";
import exportMultiRatioRouter from "./generate/export-multi-ratio";
import extractAudioRouter from "./generate/extract-audio";
import cheatCodeRouter from "./cheat-code";
import mixMasterRouter from "./generate/mix-master";
import shopsRouter from "./generate/shops";
import storefrontsRouter from "./generate/storefronts";
import showFinderRouter from "./generate/show-finder";
import brandDealsRouter from "./generate/brand-deals";
import collageRouter from "./generate/collage";
import karaokeRouter from "./generate/karaoke";
import textAnimatorRouter from "./generate/text-animator";
import subtitleStylerRouter from "./generate/subtitle-styler";
import autoCaptionsRouter from "./generate/auto-captions";
import watermarkRouter from "./generate/watermark";
import gifConverterRouter from "./generate/gif-converter";
import reverseVideoRouter from "./generate/reverse-video";
import freezeMaskRouter from "./generate/freeze-mask";
import thumbExtractRouter from "./generate/thumb-extract";
import ctrPredictorRouter from "./generate/ctr-predictor";
import bestTimeRouter from "./generate/best-time";
import quoteFinderRouter from "./generate/quote-finder";
import podcastIntroRouter from "./generate/podcast-intro";
import slideshowRouter from "./generate/slideshow";
import reactionVideoRouter from "./generate/reaction-video";
import videoDubRouter from "./generate/video-dub";

const router: IRouter = Router();

router.use(healthRouter);
router.use(songRouter);
router.use(videoRouter);
router.use(songVideoRouter);
router.use(autoVideoPlanRouter);
router.use(promoRouter);
router.use(thumbnailRouter);
router.use(projectsRouter);
router.use(hubProjectsRouter);
router.use(reviewLinksRouter);
router.use(artistVaultsRouter);
router.use(generationsRouter);
router.use(artistVoicesRouter);
router.use(locationsRouter);
router.use(artistOutfitsRouter);
router.use(songsRouter);
router.use(playlistRouter);
router.use(waitlistRouter);
router.use(contactRouter);
router.use(spotlightRouter);
router.use(transcribeRouter);
router.use(analyzeSectionsRouter);
router.use(demoClipRouter);
router.use(runwayClipRouter);
router.use(artistImageRouter);
router.use(uploadClipRouter);
router.use(adminRouter);
router.use(bowChallengeRouter);
router.use(nfcCardsRouter);
router.use(jewelryOrdersRouter);
router.use(exportVideoRouter);
router.use(prepareExportFilesRouter);
router.use(exportDoctorRouter);
router.use(improvePromptRouter);
router.use(autoEditRouter);
router.use(aiEditPlanRouter);
router.use(mixPlanRouter);
router.use(musicAudioRouter);
router.use(beatRouter);
router.use(musicExportRouter);
router.use(uploadWatermarkRouter);
router.use(devRouter);
router.use(stripePaymentsRouter);
router.use(creditsRouter);
router.use(bonusRouter);
router.use(teamsRouter);
router.use(referralsRouter);
router.use(generatedClipsRouter);
router.use(draftsRouter);
router.use(generationHistoryRouter);
router.use(thumbnailsRouter);
router.use(showcaseRouter);
router.use(lipSyncRouter);
router.use(preProductionRouter);
router.use(chatRouter);
router.use(freeChatRouter);
router.use(randomizerRouter);
router.use(hookStudioRouter);
router.use(ctaGeneratorRouter);
router.use(gamersRouter);
router.use(proToolsAiRouter);
router.use(soundFinderRouter);
router.use(monetizationCoachRouter);
router.use(brandCalculatorRouter);
router.use(academyRouter);
router.use(commentRepliesRouter);
router.use(contentCalendarRouter);
router.use(tipJarRouter);router.use(interviewPrepRouter);router.use(upscaleRouter);
router.use(titleStudioRouter);
router.use(sponsorsRouter);
router.use(brandingShopRouter);
router.use(collabsRouter);
router.use(communityRouter);
router.use(contestsRouter);
router.use(copyrightRouter);
router.use(coverArtRouter);
router.use(emailListRouter);
router.use(liveShoppingRouter);
router.use(membershipsRouter);
router.use(podcastRouter);
router.use(pressKitRouter);
router.use(pressReleaseRouter);
router.use(royaltiesRouter);
router.use(scriptWriterRouter);
router.use(sfxRouter);
router.use(thumbnailTestRouter);
router.use(trendPredictorRouter);
router.use(voiceoverRouter);
router.use(beatsRouter);
router.use(captionStylerRouter);
router.use(lyricVideoRouter);
router.use(backgroundRemovalRouter);
router.use(videoBackgroundRemovalRouter);
router.use(bgReplacerRouter);
router.use(lyricsGeneratorRouter);
router.use(autoReframeRouter);
router.use(voiceEffectsRouter);
router.use(audioDuckingRouter);
router.use(videoStylesRouter);
router.use(silenceRemovalRouter);
router.use(logoAnimatorRouter);
router.use(transitionsRouter);
router.use(videoTemplateRouter);
router.use(smartClipsRouter);
router.use(voicePersonasRouter);
router.use(voiceCloneRouter);
router.use(scriptToVideoRouter);
router.use(socialSchedulerRouter);
router.use(bgMusicRouter);
router.use(translateCaptionsRouter);
router.use(socialAnalyticsRouter);
router.use(hookAnalyzerRouter);
router.use(showNotesRouter);
router.use(autoChaptersRouter);
router.use(chaptersRouter);
router.use(voiceoverProRouter);
router.use(brollSuggesterRouter);
router.use(brandKitRouter);
router.use(speedPresetsRouter);
router.use(colorGradeRouter);
router.use(videoTrimRouter);
router.use(slowMotionRouter);
router.use(loopMakerRouter);
router.use(endScreenRouter);
router.use(thumbnailAbRouter);
router.use(thumbBgRouter);
router.use(chapterArtRouter);
router.use(socialKitRouter);
router.use(storyboardRouter);
router.use(volumeNormRouter);
router.use(stabilizeRouter);
router.use(motionTrackRouter);
router.use(videoTitlesRouter);
router.use(clipDescriptionsRouter);
router.use(descAbTestRouter);
router.use(seoScoreRouter);
router.use(thumbnailTextRouter);
router.use(audiogramRouter);
router.use(memeGeneratorRouter);
router.use(testimonialRouter);
router.use(nicheAnalyzerRouter);
router.use(ideaValidatorRouter);
router.use(hashtagsRouter);
router.use(virtualBgRouter);
router.use(masteringRouter);
router.use(bioGeneratorRouter);
router.use(communityPostRouter);
router.use(repurposeRouter);
router.use(samplePackRouter);
router.use(stemSplitterRouter);
router.use(streamerClipsRouter);
router.use(videoTranslatorRouter);
router.use(vocalRemovalRouter);
router.use(watermarkRemovalRouter);
router.use(mediaImporterRouter);
router.use(streamPackRouter);
router.use(logoRouter);
router.use(viralityCheckRouter);
router.use(upscaleImageRouter);
router.use(analyticsHubRouter);
router.use(competitorTrackerRouter);
router.use(contentPlansRouter);
router.use(introOutroRouter);
router.use(introOutroFfmpegRouter);
router.use(llcGuideRouter);
router.use(tourPlannerRouter);
router.use(setlistRouter);
router.use(promoGeneratorRouter);
router.use(socialRouter);
router.use(analyticsRouter);
router.use(discordRouter);
router.use(discordBotRouter);
router.use(jobNotificationsRouter);
router.use(distributionRouter);
router.use(schedulerRouter);
router.use(merchRouter);
router.use(jewelryRouter);
router.use(playlistPitchRouter);
router.use(labelPitchRouter);
router.use(channelAuditRouter);
router.use("/contracts", contractAnalyzerRouter);
router.use("/movies", moviesRouter);
router.use("/website-builder", websiteBuilderRouter);
router.use("/detect", mediaDetectorRouter);
router.use(sponsorshipOutreachRouter);
router.use(sponsorReadRouter);
router.use(karaokeRouter);
router.use(shoutoutsRouter);
router.use(releaseChecklistRouter);
router.use(thumbnailGeneratorRouter);
router.use(audioCleanupRouter);
router.use(aspectConvertRouter);
router.use(exportMultiRatioRouter);
router.use(extractAudioRouter);
router.use(cheatCodeRouter);
router.use(videoMergerRouter);
router.use(beatSyncRouter);
router.use(mixMasterRouter);
router.use(subtitleStylerRouter);
router.use(autoCaptionsRouter);
router.use(shopsRouter);
router.use(storefrontsRouter);
router.use(showFinderRouter);
router.use(brandDealsRouter);
router.use(collageRouter);
router.use(textAnimatorRouter);
router.use(watermarkRouter);
router.use(gifConverterRouter);
router.use(reverseVideoRouter);
router.use(freezeMaskRouter);
router.use(thumbExtractRouter);
router.use(ctrPredictorRouter);
router.use(bestTimeRouter);
router.use(quoteFinderRouter);
router.use(videoDubRouter);
router.use(podcastIntroRouter);
router.use(slideshowRouter);
router.use(reactionVideoRouter);

export default router;
