import { Router } from "express";
import multer from "multer";
import { execFile } from "child_process";
import { promisify } from "util";
import { writeFile, readFile, mkdtemp, rm } from "fs/promises";
import { existsSync, readFileSync } from "fs";
import { tmpdir } from "os";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { randomUUID } from "crypto";
import { eq, and, desc } from "drizzle-orm";
import { requireAuth } from "../middlewares/require-auth";
import { chargeCredits, refundCredits, OutOfCreditsError } from "../lib/credits";
import {
  uploadMediaToSupabaseStorage,
  refreshSupabaseStorageUrl,
} from "../lib/objectStorage";
import { db, userLutsTable } from "@workspace/db";
import { logger } from "../lib/logger";

const router = Router();
const execFileAsync = promisify(execFile);

/* ─── LUT Import (.cube / .3dl) — CapCut color parity ────────────────────
   Pure ffmpeg (lut3d filter). 150 Visual Bucs per apply; preview + validation
   + listing are free. */

/** 150 Visual Bucs per LUT apply (matches the color-grade price). */
const LUT_APPLY_COST = Number(process.env["LUT_APPLY_CREDITS"]) || 150;

const VIDEO_MAX_BYTES = 80 * 1024 * 1024; // 80 MB, same as /upload-clip
const LUT_MAX_BYTES = 5 * 1024 * 1024; // LUT files are small text

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: VIDEO_MAX_BYTES },
});

/* ── House LUTs ───────────────────────────────────────────────────────────
   4 .cube files generated by scripts/generate-house-luts.mjs, committed to
   data/luts/ (shipped inside the Docker image via COPY . .). */
/* Resolve the house-LUT data dir in both layouts:
   - esbuild bundle:   <artifact>/dist/index.mjs      -> <artifact>/data/luts
   - ts source (tests): <artifact>/src/routes/lut.ts -> <artifact>/data/luts */
function resolveLutsDir(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  const candidates = [
    join(here, "..", "data", "luts"),
    join(here, "..", "..", "data", "luts"),
  ];
  for (const c of candidates) {
    if (existsSync(join(c, "presets.json"))) return c;
  }
  return candidates[0];
}
const LUTS_DIR = resolveLutsDir();

interface HousePreset {
  id: string;
  name: string;
  description: string;
  file: string;
  swatches: string[];
}

let housePresets: HousePreset[] = [];
try {
  const raw = readFileSync(join(LUTS_DIR, "presets.json"), "utf8");
  housePresets = (JSON.parse(raw) as { presets: HousePreset[] }).presets ?? [];
} catch (err) {
  logger.warn({ err }, "[lut] could not load house presets; presets endpoint will be empty");
}

const housePresetById = (id: string): HousePreset | undefined =>
  housePresets.find((p) => p.id === id);

/* ── LUT parsing / validation ───────────────────────────────────────────── */

export interface ParsedLut {
  format: "cube" | "3dl";
  title: string;
  size: number;
  /** Normalized .cube text, ready for ffmpeg's lut3d filter. */
  cubeText: string;
}

export class LutValidationError extends Error {}

function parseCube(text: string): Omit<ParsedLut, "format" | "cubeText"> {
  const lines = text.split(/\r?\n/);
  let title = "Untitled LUT";
  let size = 0;
  const dataLines: string[] = [];

  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const upper = line.toUpperCase();
    if (upper.startsWith("TITLE")) {
      const m = line.match(/"([^"]*)"/);
      if (m) title = m[1].slice(0, 120);
      continue;
    }
    if (upper.startsWith("LUT_3D_SIZE")) {
      const n = parseInt(line.split(/\s+/)[1] ?? "", 10);
      if (!Number.isInteger(n) || n < 2 || n > 64) {
        throw new LutValidationError(
          `Invalid LUT_3D_SIZE "${line}". Expected an integer between 2 and 64.`,
        );
      }
      size = n;
      continue;
    }
    if (
      upper.startsWith("LUT_1D_SIZE") ||
      upper.startsWith("DOMAIN_MIN") ||
      upper.startsWith("DOMAIN_MAX") ||
      upper.startsWith("LUT_1D_INPUT_RANGE") ||
      upper.startsWith("LUT_3D_INPUT_RANGE")
    ) {
      continue;
    }
    dataLines.push(line);
  }

  if (!size) throw new LutValidationError("Missing LUT_3D_SIZE header — not a valid .cube file.");
  const expected = size * size * size;
  if (dataLines.length < expected) {
    throw new LutValidationError(
      `Truncated LUT data: expected ${expected.toLocaleString("en-US")} RGB triplets for LUT_3D_SIZE ${size}, found ${dataLines.length.toLocaleString("en-US")}.`,
    );
  }
  if (dataLines.length > expected) {
    throw new LutValidationError(
      `Too many data lines: expected ${expected.toLocaleString("en-US")} RGB triplets, found ${dataLines.length.toLocaleString("en-US")}.`,
    );
  }
  for (let i = 0; i < dataLines.length; i++) {
    const parts = dataLines[i].split(/\s+/).filter(Boolean);
    if (parts.length !== 3 || parts.some((p) => !/^-?\d+(\.\d+)?$/.test(p))) {
      throw new LutValidationError(`Malformed RGB triplet on data line ${i + 1}: "${dataLines[i].slice(0, 60)}".`);
    }
    for (const p of parts) {
      const v = parseFloat(p);
      if (v < -0.02 || v > 1.02) {
        throw new LutValidationError(
          `LUT value out of range on data line ${i + 1}: values must be between 0 and 1.`,
        );
      }
    }
  }
  return { title, size };
}

/** Parse an IRIDAS .3dl file and normalize it to .cube text. */
function parse3dl(text: string): Omit<ParsedLut, "format" | "cubeText"> & { cubeText: string } {
  const dataLines: string[] = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    dataLines.push(line);
  }
  if (dataLines.length < 8) {
    throw new LutValidationError("Not a valid .3dl file: expected RGB triplet data lines.");
  }
  const n = Math.round(Math.cbrt(dataLines.length));
  if (n < 4 || n > 64 || n * n * n !== dataLines.length) {
    throw new LutValidationError(
      `Invalid .3dl data: ${dataLines.length.toLocaleString("en-US")} lines is not a perfect cube (n³). Supported lattice sizes: 4–64.`,
    );
  }
  // 3dl files are commonly 0–1023; normalize to 0–1.
  let maxSeen = 0;
  const triples: number[][] = dataLines.map((line, i) => {
    const parts = line.split(/\s+/).filter(Boolean);
    if (parts.length !== 3 || parts.some((p) => !/^-?\d+(\.\d+)?$/.test(p))) {
      throw new LutValidationError(`Malformed RGB triplet on .3dl line ${i + 1}.`);
    }
    const vals = parts.map(Number);
    for (const v of vals) maxSeen = Math.max(maxSeen, v);
    return vals;
  });
  const scale = maxSeen > 1.5 ? 1023 : 1;
  const out: string[] = [
    'TITLE "Converted from .3dl — Bow Down Visuals"',
    `LUT_3D_SIZE ${n}`,
    "DOMAIN_MIN 0.0 0.0 0.0",
    "DOMAIN_MAX 1.0 1.0 1.0",
    "",
  ];
  for (const [r, g, b] of triples) {
    out.push(
      `${Math.min(1, Math.max(0, r! / scale)).toFixed(6)} ${Math.min(1, Math.max(0, g! / scale)).toFixed(6)} ${Math.min(1, Math.max(0, b! / scale)).toFixed(6)}`,
    );
  }
  return { title: "Converted .3dl LUT", size: n, cubeText: out.join("\n") + "\n" };
}

/** Validate an uploaded LUT buffer. Throws LutValidationError with a user-facing message. */
export function validateLutBuffer(buffer: Buffer, originalName: string): ParsedLut {
  if (!buffer || buffer.length < 20) {
    throw new LutValidationError("That file is empty or too small to be a LUT.");
  }
  if (buffer.length > LUT_MAX_BYTES) {
    throw new LutValidationError("That LUT file is too large (max 5 MB).");
  }
  const text = buffer.toString("utf8");
  if (text.includes("\uFFFD")) {
    throw new LutValidationError("That file isn't readable LUT text — it may be binary or corrupted.");
  }
  const ext = (originalName.split(".").pop() ?? "").toLowerCase();
  if (ext === "3dl") {
    const parsed = parse3dl(text);
    return { format: "3dl", ...parsed };
  }
  if (ext === "cube" || ext === "") {
    const parsed = parseCube(text);
    return { format: "cube", title: parsed.title, size: parsed.size, cubeText: text };
  }
  throw new LutValidationError(`Unsupported LUT format ".${ext}" — upload a .cube or .3dl file.`);
}

/* ── LUT resolution ───────────────────────────────────────────────────────
   Every mutating endpoint accepts the LUT as: uploaded file > presetId >
   saved lutId. Returns the normalized .cube text + a display name. */
async function resolveLut(
  req: { file?: Express.Multer.File; body: Record<string, unknown>; userId?: string },
  workDir: string,
): Promise<{ cubePath: string; displayName: string }> {
  const body = req.body ?? {};
  const presetId = typeof body.presetId === "string" ? body.presetId : "";
  const lutId = typeof body.lutId === "string" ? body.lutId : "";
  const lutFile = uploadedFile(req, "lut");

  if (lutFile) {
    const parsed = validateLutBuffer(lutFile.buffer, lutFile.originalname);
    const cubePath = join(workDir, `lut-${randomUUID()}.cube`);
    await writeFile(cubePath, parsed.cubeText);
    return { cubePath, displayName: parsed.title };
  }
  if (presetId) {
    const preset = housePresetById(presetId);
    if (!preset) throw new LutValidationError(`Unknown preset "${presetId}".`);
    const cubePath = join(workDir, `lut-${randomUUID()}.cube`);
    await writeFile(cubePath, await readFile(join(LUTS_DIR, `${preset.id}.cube`), "utf8"));
    return { cubePath, displayName: preset.name };
  }
  if (lutId) {
    if (!req.userId) throw new LutValidationError("Sign in to use a saved LUT.");
    const [row] = await db
      .select()
      .from(userLutsTable)
      .where(and(eq(userLutsTable.id, lutId), eq(userLutsTable.user_id, req.userId)))
      .limit(1);
    if (!row) throw new LutValidationError("That saved LUT wasn't found.");
    const storageUrl = await refreshSupabaseStorageUrl(row.storage_ref);
    const dl = await fetch(storageUrl, { signal: AbortSignal.timeout(60_000) });
    if (!dl.ok) throw new Error("Could not download the saved LUT.");
    const parsed = validateLutBuffer(
      Buffer.from(await dl.arrayBuffer()),
      row.format === "3dl" ? "saved.3dl" : "saved.cube",
    );
    const cubePath = join(workDir, `lut-${randomUUID()}.cube`);
    await writeFile(cubePath, parsed.cubeText);
    return { cubePath, displayName: row.name };
  }
  throw new LutValidationError("No LUT provided — upload a .cube/.3dl file or pick a preset.");
}

/** Grab an uploaded file by field name — works with multer .single() and .fields(). */
function uploadedFile(req: unknown, field: string): Express.Multer.File | undefined {
  const r = req as {
    file?: Express.Multer.File;
    files?: Express.Multer.File[] | Record<string, Express.Multer.File[]>;
  };
  if (Array.isArray(r.files)) return r.files.find((f) => f.fieldname === field);
  return r.files?.[field]?.[0] ?? (r.file?.fieldname === field ? r.file : undefined);
}

/** Fetch the source video (uploaded file or videoUrl) into the work dir. */
async function fetchVideo(
  req: unknown,
  workDir: string,
  body: Record<string, unknown>,
): Promise<string> {
  const inputPath = join(workDir, "input.mp4");
  const videoFile = uploadedFile(req, "video") ?? uploadedFile(req, "clip");
  if (videoFile) {
    if (!videoFile.mimetype.startsWith("video/")) {
      throw new LutValidationError("The uploaded clip isn't a video file.");
    }
    await writeFile(inputPath, videoFile.buffer);
    return inputPath;
  }
  let videoUrl = typeof body.videoUrl === "string" ? body.videoUrl.trim() : "";
  if (!videoUrl) throw new LutValidationError("No video provided — upload a clip or pass videoUrl.");
  if (videoUrl.length > 4096) throw new LutValidationError("videoUrl is too long.");
  // Accept supabase:// storage refs as well as signed/public URLs.
  videoUrl = await refreshSupabaseStorageUrl(videoUrl);
  const res = await fetch(videoUrl, { signal: AbortSignal.timeout(180_000) });
  if (!res.ok) throw new Error("Could not download the video (check the URL).");
  await writeFile(inputPath, Buffer.from(await res.arrayBuffer()));
  return inputPath;
}

type JsonResponder = { status: (code: number) => { json: (body: unknown) => void } };

function isLutValidationError(err: unknown): err is LutValidationError {
  return err instanceof LutValidationError;
}

function sendLutError(res: JsonResponder, err: unknown, req: { log: { error: (obj: unknown, msg: string) => void } }, tag: string): void {
  if (isLutValidationError(err)) {
    res.status(400).json({ error: err.message });
    return;
  }
  const message = err instanceof Error ? err.message : "Request failed.";
  req.log.error({ err: message }, tag);
  res.status(500).json({ error: message });
}

/* ── Routes ─────────────────────────────────────────────────────────────── */

/** GET /api/lut/presets — the 4 built-in house LUTs. Public, free. */
router.get("/lut/presets", (_req, res) => {
  res.json({ presets: housePresets });
});

/** GET /api/lut/presets/:file — serve a house .cube file. Public, free. */
router.get("/lut/presets/:file", (req, res) => {
  const file = String(req.params.file ?? "");
  const preset = housePresets.find((p) => `${p.id}.cube` === file);
  if (!preset) {
    res.status(404).json({ error: "LUT preset not found." });
    return;
  }
  res.type("text/plain").sendFile(join(LUTS_DIR, `${preset.id}.cube`));
});

/**
 * POST /api/lut/validate — validate an uploaded LUT without spending.
 * multipart: lut (file). Free.
 */
router.post("/lut/validate", requireAuth, upload.single("lut"), (req, res) => {
  try {
    if (!req.file) {
      res.status(400).json({ error: "Upload a .cube or .3dl file in the 'lut' field." });
      return;
    }
    const parsed = validateLutBuffer(req.file.buffer, req.file.originalname);
    res.json({
      valid: true,
      format: parsed.format,
      title: parsed.title,
      size: parsed.size,
    });
  } catch (err) {
    if (err instanceof LutValidationError) {
      res.status(400).json({ valid: false, error: err.message });
      return;
    }
    throw err;
  }
});

/**
 * POST /api/lut/preview — free thumbnail preview of the LUT on a video frame.
 * multipart: video (file) | videoUrl (field); lut (file) | presetId | lutId (fields).
 * Returns a JPEG of the middle frame with the LUT applied.
 */
router.post(
  "/lut/preview",
  requireAuth,
  upload.fields([
    { name: "video", maxCount: 1 },
    { name: "lut", maxCount: 1 },
  ]),
  async (req, res) => {
    const workDir = await mkdtemp(join(tmpdir(), "lutpreview-"));
    try {
      const inputPath = await fetchVideo(req, workDir, (req.body ?? {}) as Record<string, unknown>);
      const { cubePath } = await resolveLut(req, workDir);

      // Seek to the middle of the clip for a representative frame.
      let seekSec = 1;
      try {
        const { stdout } = await execFileAsync(
          "ffprobe",
          ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", inputPath],
          { timeout: 30_000 },
        );
        const dur = parseFloat((stdout ?? "").trim());
        if (Number.isFinite(dur) && dur > 0) seekSec = Math.max(0.2, dur / 2);
      } catch { /* fall back to 1s */ }

      const outPath = join(workDir, "preview.jpg");
      await execFileAsync(
        "ffmpeg",
        [
          "-y",
          "-ss", String(seekSec),
          "-i", inputPath,
          "-vframes", "1",
          "-vf", `lut3d=file='${cubePath}',scale=640:-2`,
          "-q:v", "4",
          outPath,
        ],
        { timeout: 120_000 },
      );
      res.type("image/jpeg").send(await readFile(outPath));
    } catch (err) {
      sendLutError(res, err, req, "[lut] preview failed");
    } finally {
      await rm(workDir, { recursive: true, force: true }).catch(() => {});
    }
  },
);

/**
 * POST /api/apply-lut — burn a LUT into a clip via ffmpeg lut3d.
 * multipart: video (file) | videoUrl (field); lut (file) | presetId | lutId (fields).
 * 150 Visual Bucs. Auto-refund on failure.
 */
router.post(
  "/apply-lut",
  requireAuth,
  upload.fields([
    { name: "video", maxCount: 1 },
    { name: "lut", maxCount: 1 },
  ]),
  async (req, res) => {
    const currentCredits = req.userCredits ?? 0;
    if (currentCredits < LUT_APPLY_COST) {
      res.status(402).json({
        error: "out_of_credits",
        message: `Not enough Visual Bucs — this costs ${LUT_APPLY_COST.toLocaleString("en-US")} Visual Bucs.`,
        required: LUT_APPLY_COST,
        balance: currentCredits,
      });
      return;
    }

    const workDir = await mkdtemp(join(tmpdir(), "lutapply-"));
    let charged = false;
    let displayName = "LUT";
    try {
      const inputPath = await fetchVideo(req, workDir, (req.body ?? {}) as Record<string, unknown>);
      const resolved = await resolveLut(req, workDir);
      displayName = resolved.displayName;

      let creditsAfter: number;
      try {
        creditsAfter = await chargeCredits(req.userId!, LUT_APPLY_COST, {
          action: `LUT apply (${displayName})`,
        });
        charged = true;
      } catch (err) {
        if (err instanceof OutOfCreditsError) {
          res.status(402).json({ error: "out_of_credits", message: "Not enough Visual Bucs." });
          return;
        }
        throw err;
      }

      const outputPath = join(workDir, "output.mp4");
      await execFileAsync(
        "ffmpeg",
        [
          "-y",
          "-i", inputPath,
          "-vf", `lut3d=file='${resolved.cubePath}'`,
          "-c:v", "libx264",
          "-preset", "fast",
          "-crf", "18",
          "-pix_fmt", "yuv420p",
          "-c:a", "copy",
          outputPath,
        ],
        { timeout: 600_000 },
      );

      const buffer = await readFile(outputPath);
      const objectName = `lutgrade/${req.userId}/${randomUUID()}.mp4`;
      const storageRef = await uploadMediaToSupabaseStorage(objectName, buffer, "video/mp4");
      const url = await refreshSupabaseStorageUrl(storageRef);

      res.json({ url, storageRef, lut: displayName, creditsRemaining: creditsAfter });
    } catch (err) {
      if (charged) {
        await refundCredits(req.userId!, LUT_APPLY_COST, {
          action: "LUT apply — Refund",
        }).catch(() => {});
      }
      sendLutError(res, err, req, "[lut] apply failed");
    } finally {
      await rm(workDir, { recursive: true, force: true }).catch(() => {});
    }
  },
);

/**
 * POST /api/lut/upload — save a validated LUT to "My LUTs" for reuse.
 * multipart: lut (file); optional field: name. Free.
 */
router.post("/lut/upload", requireAuth, upload.single("lut"), async (req, res) => {
  try {
    if (!req.file) {
      res.status(400).json({ error: "Upload a .cube or .3dl file in the 'lut' field." });
      return;
    }
    const parsed = validateLutBuffer(req.file.buffer, req.file.originalname);
    const name =
      (typeof req.body?.name === "string" && req.body.name.trim().slice(0, 80)) ||
      parsed.title ||
      req.file.originalname.replace(/\.[^.]+$/, "");
    const ext = parsed.format === "3dl" ? "3dl" : "cube";
    const objectName = `luts/${req.userId}/${randomUUID()}.${ext}`;
    const storageRef = await uploadMediaToSupabaseStorage(
      objectName,
      Buffer.from(parsed.cubeText, "utf8"),
      "text/plain",
    );
    const [row] = await db
      .insert(userLutsTable)
      .values({
        user_id: req.userId!,
        name,
        format: parsed.format,
        lut_size: parsed.size,
        storage_ref: storageRef,
      })
      .returning();
    const url = await refreshSupabaseStorageUrl(storageRef).catch(() => null);
    res.json({
      id: row!.id,
      name: row!.name,
      format: row!.format,
      size: row!.lut_size,
      url,
      createdAt: row!.created_at,
    });
  } catch (err) {
    sendLutError(res, err, req, "[lut] upload failed");
  }
});

/** GET /api/lut/my — list the user's saved LUTs. Free. */
router.get("/lut/my", requireAuth, async (req, res) => {
  try {
    const rows = await db
      .select()
      .from(userLutsTable)
      .where(eq(userLutsTable.user_id, req.userId!))
      .orderBy(desc(userLutsTable.created_at));
    const items = await Promise.all(
      rows.map(async (r) => ({
        id: r.id,
        name: r.name,
        format: r.format,
        size: r.lut_size,
        url: await refreshSupabaseStorageUrl(r.storage_ref).catch(() => null),
        createdAt: r.created_at,
      })),
    );
    res.json({ luts: items });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Failed to load saved LUTs.";
    req.log.error({ err: message }, "[lut] my-list failed");
    res.status(500).json({ error: message });
  }
});

/** DELETE /api/lut/my/:id — delete a saved LUT. Free. */
router.delete("/lut/my/:id", requireAuth, async (req, res) => {
  try {
    const id = String(req.params.id ?? "");
    const deleted = await db
      .delete(userLutsTable)
      .where(and(eq(userLutsTable.id, id), eq(userLutsTable.user_id, req.userId!)))
      .returning({ id: userLutsTable.id });
    if (deleted.length === 0) {
      res.status(404).json({ error: "Saved LUT not found." });
      return;
    }
    res.json({ deleted: true });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Failed to delete the LUT.";
    req.log.error({ err: message }, "[lut] delete failed");
    res.status(500).json({ error: message });
  }
});

export default router;
