// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/artist-theme/VariantA.tsx": () => import("../components/mockups/artist-theme/VariantA.tsx")
};
