import {
  Drum, Scissors, Disc3, Clapperboard, Megaphone, Lightbulb, PenLine,
  Mic2, Film, Image as ImageIcon, ShieldCheck, Palette, FlaskConical,
  Users, MapPin, Copyright, Rocket, ListChecks, CalendarDays, Coins,
  TrendingUp, BarChart3, GraduationCap, BookOpen, Scale, Briefcase,
  FileText, Newspaper, Mail, Handshake, Store, Banknote, Shirt, Flame,
  Type as TypeIcon, Gamepad2, Zap, Tv, AudioWaveform, Subtitles, Captions,
  Package, Play, Video as VideoIcon, Shapes, Maximize, Stamp, MonitorPlay, ListMusic,
  RefreshCw, Languages, MessageCircle, UserPlus, Trophy, FileSearch, Calculator,
  Send, DollarSign, ShoppingBag, ShoppingCart, Ticket, Presentation, Podcast,
  Gem, Wand2, ScanSearch,
  type LucideIcon,
} from "lucide-react";
import type { HubAssetKind, HubProjectType } from "./hub-project";

/* ─── Project-type workflows ───────────────────────────────────────────────
   One hub, many crafts. The project's type decides the chain: a song flows
   Beat → Stems → Song → Video → Promo; a video flows Hook → Script →
   Voiceover → Clips → Thumbnail; a visual package flows Vault → Thumbnail →
   Cover → Brand → Test. Every step feeds the next — that's the whole point. */

export interface WorkflowStep {
  key: string;
  label: string;
  icon: LucideIcon;
  /** Which asset kind marks this step done (null = launcher only). */
  assetKind: HubAssetKind | null;
  href: string;
  blurb: string;
  creditNote: string;
  /** Inline module rendered in the hub stage instead of a launcher card. */
  embed?: "beat-maker" | "thumbnail-maker";
  /** Custom label for the guided-mode skip button (default: "Skip for now"). */
  skipLabel?: string;
}

export type HubFamily = "create" | "launch" | "grow" | "monetize" | "learn" | "business";

export const FAMILIES: { key: HubFamily; label: string; blurb: string }[] = [
  { key: "create", label: "Create", blurb: "Make the thing" },
  { key: "launch", label: "Launch", blurb: "Ship it right" },
  { key: "grow", label: "Grow", blurb: "Get seen" },
  { key: "monetize", label: "Monetize", blurb: "Get paid" },
  { key: "learn", label: "Learn", blurb: "Level up" },
  { key: "business", label: "Business", blurb: "Handle the paperwork" },
];

export interface ProjectWorkflow {
  type: HubProjectType;
  family: HubFamily;
  title: string;
  tagline: string;
  icon: LucideIcon;
  steps: WorkflowStep[];
}

export const PROJECT_WORKFLOWS: ProjectWorkflow[] = [
  {
    type: "song",
    family: "create",
    title: "Song",
    tagline: "Samples → beat → song → master → video → promo. The full record, start to finish.",
    icon: Disc3,
    steps: [
      { key: "samples", label: "Samples", icon: Package, assetKind: null, href: "/samples",
        blurb: "Need sounds? Generate a sample pack to chop and flip.",
        creditNote: "100 Visual Bucs" },
      { key: "brand", label: "Brand", icon: ShieldCheck, assetKind: null, href: "/artist-vault",
        blurb: "Brand your AI artist — face, voice, and look, locked so the AI never breaks character.",
        creditNote: "free" },
      { key: "beat", label: "Beat", icon: Drum, assetKind: "beat", href: "/hub",
        blurb: "AI-generate an instrumental or program drums on the step sequencer.",
        creditNote: "300 Visual Bucs · sequencer free", embed: "beat-maker" },
      { key: "stems", label: "Stems", icon: Scissors, assetKind: "stems", href: "/stems",
        blurb: "Split any audio into vocals, drums, bass, and melody stems.",
        creditNote: "400 Visual Bucs" },
      { key: "song", label: "Song", icon: Disc3, assetKind: "song", href: "/make-song",
        blurb: "Turn the beat into a full song with AI vocals and arrangement.",
        creditNote: "400 Visual Bucs" },
      { key: "master", label: "Master", icon: AudioWaveform, assetKind: null, href: "/mastering",
        blurb: "Radio-ready master — loud, clean, polished.",
        creditNote: "200 Visual Bucs" },
      { key: "video", label: "Video", icon: Clapperboard, assetKind: "video", href: "/make-video",
        blurb: "Generate the music video — scenes, lip sync, full edit.",
        creditNote: "from 400 Visual Bucs" },
      { key: "lyricvideo", label: "Lyric Video", icon: Subtitles, assetKind: null, href: "/lyric-video",
        blurb: "A lyric video for the song — another way to get seen.",
        creditNote: "from 200 Visual Bucs" },
      { key: "promo", label: "Promo", icon: Megaphone, assetKind: "clip", href: "/promo-clip",
        blurb: "Cut promo clips, make the thumbnail, ship it everywhere.",
        creditNote: "from 100 Visual Bucs" },
      { key: "getpaid", label: "Get Paid", icon: Coins, assetKind: null, href: "/coach",
        blurb: "The way to the money — your AI coach builds the gameplan: sponsors, pricing, revenue streams.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "video",
    family: "create",
    title: "Video",
    tagline: "Hook → script → voiceover → clips → thumbnail. Content that stops the scroll.",
    icon: Clapperboard,
    steps: [
      { key: "hook", label: "Hook", icon: Lightbulb, assetKind: null, href: "/hooks",
        blurb: "Generate hooks engineered to stop the scroll in the first 3 seconds.",
        creditNote: "100 Visual Bucs" },
      { key: "brand", label: "Brand", icon: Palette, assetKind: null, href: "/branding-kit",
        blurb: "Brand your channel — logo, colors, and intros people recognize instantly.",
        creditNote: "varies" },
      { key: "script", label: "Script", icon: PenLine, assetKind: "script", href: "/script-writer",
        blurb: "Turn the hook into a full script — pacing, beats, and CTAs included.",
        creditNote: "200 Visual Bucs" },
      { key: "voiceover", label: "Voiceover", icon: Mic2, assetKind: "song", href: "/voiceover",
        blurb: "AI voiceover in your locked voice, timed to the script.",
        creditNote: "200 Visual Bucs" },
      { key: "clips", label: "Clips", icon: Film, assetKind: "clip", href: "/promo-clip",
        blurb: "Cut the video into platform-ready clips — vertical, captioned, posted.",
        creditNote: "from 100 Visual Bucs" },
      { key: "streamclips", label: "Stream Clips", icon: VideoIcon, assetKind: null, href: "/clip-maker",
        blurb: "Streamed it? AI cuts your VOD into the best moments.",
        creditNote: "varies" },
      { key: "captions", label: "Captions", icon: Captions, assetKind: null, href: "/caption-styler",
        blurb: "Captions that pop — styled word by word.",
        creditNote: "300 Visual Bucs" },
      { key: "thumbnail", label: "Thumbnail", icon: ImageIcon, assetKind: "thumbnail", href: "/thumbnail-maker",
        blurb: "The thumbnail that gets the click — then A/B test it.",
        creditNote: "200 Visual Bucs", embed: "thumbnail-maker" },
      { key: "intros", label: "Intros", icon: Play, assetKind: null, href: "/intros-outros",
        blurb: "Your branded intro and outro on every video.",
        creditNote: "200 Visual Bucs" },
      { key: "getpaid", label: "Get Paid", icon: Coins, assetKind: null, href: "/coach",
        blurb: "The way to the money — your AI coach builds the gameplan: sponsors, pricing, revenue streams.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "visual",
    family: "create",
    title: "Visuals & Brand",
    tagline: "Vault → thumbnail → cover → brand → test. The look, locked and shipped.",
    icon: Palette,
    steps: [
      { key: "vault", label: "Identity", icon: ShieldCheck, assetKind: null, href: "/artist-vault",
        blurb: "Lock your look in the Creator Vault — face, style, and rules AI must never break.",
        creditNote: "free" },
      { key: "logo", label: "Logo", icon: Shapes, assetKind: null, href: "/logo-maker",
        blurb: "Your logo — generated around your locked identity.",
        creditNote: "100 Visual Bucs" },
      { key: "thumbnail", label: "Thumbnail", icon: ImageIcon, assetKind: "thumbnail", href: "/thumbnail-maker",
        blurb: "Scroll-stopping thumbnails in your locked identity.",
        creditNote: "200 Visual Bucs", embed: "thumbnail-maker" },
      { key: "cover", label: "Cover Art", icon: Disc3, assetKind: "image", href: "/cover-art",
        blurb: "Single and album artwork with art direction that matches the music.",
        creditNote: "200–300 Visual Bucs" },
      { key: "upscale", label: "Upscale", icon: Maximize, assetKind: null, href: "/upscale",
        blurb: "4K sharp — upscale any visual you just made.",
        creditNote: "300 Visual Bucs" },
      { key: "watermark", label: "De-watermark", icon: Stamp, assetKind: null, href: "/watermark-removal",
        blurb: "Clean 4K, no watermark — strip marks off your own content.",
        creditNote: "200 Visual Bucs" },
      { key: "brand", label: "Brand Kit", icon: Palette, assetKind: null, href: "/branding-kit",
        blurb: "Logos, intros, outros, and stream assets in one consistent brand.",
        creditNote: "varies" },
      { key: "streampack", label: "Stream Pack", icon: MonitorPlay, assetKind: null, href: "/stream-pack",
        blurb: "Overlays, alerts, panels — your whole stream look in one pack.",
        creditNote: "200 Visual Bucs" },
      { key: "test", label: "A/B Test", icon: FlaskConical, assetKind: null, href: "/thumbnail-test",
        blurb: "Let the data pick the winner before you publish.",
        creditNote: "100 Visual Bucs" },
      { key: "getpaid", label: "Get Paid", icon: Coins, assetKind: null, href: "/coach",
        blurb: "The way to the money — your AI coach builds the gameplan: sponsors, pricing, revenue streams.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "movie",
    family: "create",
    title: "Movie",
    tagline: "Idea → script → cast → locations → scenes → dialogue → score → edit → premiere. The whole production, one step after the other.",
    icon: Film,
    steps: [
      { key: "idea", label: "Idea", icon: Lightbulb, assetKind: null, href: "/randomizer",
        blurb: "The spark — concept, title, and logline for your film.",
        creditNote: "free" },
      { key: "brand", label: "Brand", icon: Shapes, assetKind: null, href: "/logo-maker",
        blurb: "Brand the film — logo and title treatment that sells the poster.",
        creditNote: "100 Visual Bucs" },
      { key: "script", label: "Script", icon: PenLine, assetKind: "script", href: "/script-writer",
        blurb: "The full screenplay — beats, dialogue, and pacing.",
        creditNote: "200 Visual Bucs" },
      { key: "cast", label: "Cast", icon: Users, assetKind: null, href: "/artist-vault",
        blurb: "Lock your characters' faces so the AI never recasts them mid-film.",
        creditNote: "free" },
      { key: "locations", label: "Locations", icon: MapPin, assetKind: null, href: "/locations",
        blurb: "Scout and lock every set before cameras roll.",
        creditNote: "free" },
      { key: "scenes", label: "Scenes", icon: Clapperboard, assetKind: "video", href: "/make-video",
        blurb: "Generate every scene — storyboard to final frame.",
        creditNote: "from 400 Visual Bucs" },
      { key: "dialogue", label: "Dialogue", icon: Mic2, assetKind: "song", href: "/voiceover",
        blurb: "Every line delivered, in every character's own voice.",
        creditNote: "200 Visual Bucs" },
      { key: "score", label: "Score", icon: Drum, assetKind: "beat", href: "/hub",
        blurb: "The soundtrack — AI-composed or programmed to picture.",
        creditNote: "300 Visual Bucs · sequencer free", embed: "beat-maker" },
      { key: "edit", label: "Edit", icon: Scissors, assetKind: null, href: "/video-editor",
        blurb: "The final cut — scenes, dialogue, and score assembled.",
        creditNote: "400 Visual Bucs" },
      { key: "premiere", label: "Premiere", icon: Megaphone, assetKind: "clip", href: "/promo-clip",
        blurb: "Trailer, poster, and the big launch.",
        creditNote: "from 100 Visual Bucs" },
      { key: "getpaid", label: "Get Paid", icon: Coins, assetKind: null, href: "/coach",
        blurb: "The way to the money — your AI coach builds the gameplan: sponsors, pricing, revenue streams.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "series",
    family: "create",
    title: "TV / Web Series",
    tagline: "Concept → season arc → episodes → cast → locations → scenes → dialogue → score → edit → premiere. The whole season, one step after the other.",
    icon: Tv,
    steps: [
      { key: "concept", label: "Concept", icon: Lightbulb, assetKind: null, href: "/randomizer",
        blurb: "The spark — premise, tone, and title for your series.",
        creditNote: "free" },
      { key: "brand", label: "Brand", icon: Shapes, assetKind: null, href: "/logo-maker",
        blurb: "Brand the series — logo and title treatment for every episode.",
        creditNote: "100 Visual Bucs" },
      { key: "arc", label: "Season Arc", icon: PenLine, assetKind: "script", href: "/script-writer",
        blurb: "The season bible — character arcs, episode breakdowns, cliffhangers.",
        creditNote: "200 Visual Bucs" },
      { key: "episodes", label: "Episodes", icon: FileText, assetKind: "script", href: "/script-writer",
        blurb: "Every episode scripted — cold opens, acts, and buttons.",
        creditNote: "200 Visual Bucs" },
      { key: "cast", label: "Cast", icon: Users, assetKind: null, href: "/artist-vault",
        blurb: "Lock your series regulars so the AI never recasts them mid-season.",
        creditNote: "free" },
      { key: "locations", label: "Locations", icon: MapPin, assetKind: null, href: "/locations",
        blurb: "Standing sets and recurring locations, locked for every episode.",
        creditNote: "free" },
      { key: "scenes", label: "Scenes", icon: Clapperboard, assetKind: "video", href: "/make-video",
        blurb: "Generate every scene — episode by episode, storyboard to final frame.",
        creditNote: "from 400 Visual Bucs" },
      { key: "dialogue", label: "Dialogue", icon: Mic2, assetKind: "song", href: "/voiceover",
        blurb: "Every line delivered, in every character's own voice.",
        creditNote: "200 Visual Bucs" },
      { key: "score", label: "Score", icon: Drum, assetKind: "beat", href: "/hub",
        blurb: "Theme song, episode scores, and stingers — AI-composed or programmed to picture.",
        creditNote: "300 Visual Bucs · sequencer free", embed: "beat-maker" },
      { key: "edit", label: "Edit", icon: Scissors, assetKind: null, href: "/video-editor",
        blurb: "The final cut — every episode assembled.",
        creditNote: "400 Visual Bucs" },
      { key: "premiere", label: "Premiere", icon: Megaphone, assetKind: "clip", href: "/promo-clip",
        blurb: "Trailer, teasers, and the episode rollout.",
        creditNote: "from 100 Visual Bucs" },
      { key: "getpaid", label: "Get Paid", icon: Coins, assetKind: null, href: "/coach",
        blurb: "The way to the money — your AI coach builds the gameplan: sponsors, pricing, revenue streams.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "game",
    family: "create",
    title: "Video Game",
    tagline: "Concept → story → characters → art → soundtrack → sound FX → voices. Every asset your game needs, one step after the other.",
    icon: Gamepad2,
    steps: [
      { key: "concept", label: "Concept", icon: Lightbulb, assetKind: null, href: "/randomizer",
        blurb: "The spark — genre, hook, and title for your game.",
        creditNote: "free" },
      { key: "brand", label: "Brand", icon: Shapes, assetKind: null, href: "/logo-maker",
        blurb: "Brand the game — logo and key-art lockup.",
        creditNote: "100 Visual Bucs" },
      { key: "story", label: "Story", icon: PenLine, assetKind: "script", href: "/script-writer",
        blurb: "The full story — world, quests, and dialogue trees.",
        creditNote: "200 Visual Bucs" },
      { key: "characters", label: "Characters", icon: Users, assetKind: null, href: "/artist-vault",
        blurb: "Design and lock every character's look so the AI never redraws them mid-game.",
        creditNote: "free" },
      { key: "art", label: "Game Art", icon: ImageIcon, assetKind: "image", href: "/cover-art",
        blurb: "Sprites, key art, backgrounds, and item icons.",
        creditNote: "200–300 Visual Bucs" },
      { key: "soundtrack", label: "Soundtrack", icon: Drum, assetKind: "beat", href: "/hub",
        blurb: "The score — battle themes, ambient loops, victory stingers.",
        creditNote: "300 Visual Bucs · sequencer free", embed: "beat-maker" },
      { key: "sfx", label: "Sound FX", icon: Zap, assetKind: "sfx", href: "/sfx",
        blurb: "Jumps, hits, coins, UI clicks — every sound your game makes.",
        creditNote: "100 Visual Bucs each" },
      { key: "voices", label: "Voices", icon: Mic2, assetKind: "song", href: "/voiceover",
        blurb: "Every line delivered in each character's own voice.",
        creditNote: "200 Visual Bucs" },
      { key: "promote", label: "Promote", icon: Gamepad2, assetKind: null, href: "/gamers",
        blurb: "Get gamers hyped — content ideas built around your game.",
        creditNote: "100 Visual Bucs" },
      { key: "getpaid", label: "Get Paid", icon: Coins, assetKind: null, href: "/coach",
        blurb: "The way to the money — your AI coach builds the gameplan: sponsors, pricing, revenue streams.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "podcast",
    family: "create",
    title: "Podcast",
    tagline: "Idea → episode → video → clips. Your show, seen and heard.",
    icon: Podcast,
    steps: [
      { key: "concept", label: "Concept", icon: Lightbulb, assetKind: null, href: "/randomizer",
        blurb: "The spark — show premise, name, and angle.",
        creditNote: "free" },
      { key: "brand", label: "Brand", icon: Palette, assetKind: null, href: "/branding-kit",
        blurb: "Brand the show — the look and sound people remember.",
        creditNote: "varies" },
      { key: "script", label: "Script", icon: PenLine, assetKind: "script", href: "/script-writer",
        blurb: "Every episode scripted — intros, segments, outros.",
        creditNote: "200 Visual Bucs" },
      { key: "episode", label: "Episode", icon: Podcast, assetKind: null, href: "/podcast",
        blurb: "Generate the episode — AI voices, studio quality.",
        creditNote: "300 Visual Bucs" },
      { key: "cleanup", label: "Clean Up", icon: Wand2, assetKind: null, href: "/audio-cleanup",
        blurb: "Studio-clean audio — noise and hiss gone.",
        creditNote: "300 Visual Bucs" },
      { key: "cover", label: "Cover", icon: ImageIcon, assetKind: "image", href: "/cover-art",
        blurb: "Cover art that pops in the feed.",
        creditNote: "from 100 Visual Bucs" },
      { key: "video", label: "Video Episode", icon: Clapperboard, assetKind: "video", href: "/make-video",
        blurb: "The visual podcast — your episode as a watchable video. Or keep it audio-only.",
        creditNote: "from 400 Visual Bucs", skipLabel: "Keep it audio-only" },
      { key: "clips", label: "Clips", icon: Film, assetKind: "clip", href: "/promo-clip",
        blurb: "Cut the episode into clips that pull in new listeners.",
        creditNote: "from 100 Visual Bucs" },
      { key: "getpaid", label: "Get Paid", icon: Coins, assetKind: null, href: "/coach",
        blurb: "The way to the money — your AI coach builds the gameplan: sponsors, pricing, revenue streams.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "ai-producer",
    family: "create",
    title: "AI Producer",
    tagline: "Persona → brand → beats → placements. Your AI producer, cooking and cashing in.",
    icon: Drum,
    steps: [
      { key: "persona", label: "Persona", icon: Lightbulb, assetKind: null, href: "/randomizer",
        blurb: "Invent them — name, sound, story.",
        creditNote: "free" },
      { key: "brand", label: "Brand", icon: ShieldCheck, assetKind: null, href: "/artist-vault",
        blurb: "Lock their face and look — the AI never breaks character.",
        creditNote: "free" },
      { key: "beats", label: "Beats", icon: Drum, assetKind: "beat", href: "/hub",
        blurb: "Cook up beats in their signature sound.",
        creditNote: "300 Visual Bucs · sequencer free", embed: "beat-maker" },
      { key: "tag", label: "Tag", icon: Mic2, assetKind: null, href: "/voiceover",
        blurb: "Their producer tag — stamped on every beat.",
        creditNote: "200 Visual Bucs" },
      { key: "songs", label: "Songs", icon: Disc3, assetKind: "song", href: "/make-song",
        blurb: "Full songs built on their beats.",
        creditNote: "400 Visual Bucs" },
      { key: "content", label: "Content", icon: CalendarDays, assetKind: null, href: "/content-calendar",
        blurb: "Beat videos and studio content that sells the sound.",
        creditNote: "100 Visual Bucs" },
      { key: "placements", label: "Placements", icon: Handshake, assetKind: null, href: "/brand-deals",
        blurb: "Sell beats and land placements.",
        creditNote: "200 Visual Bucs/search" },
      { key: "getpaid", label: "Get Paid", icon: Coins, assetKind: null, href: "/coach",
        blurb: "The way to the money — the producer money playbook.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "release",
    family: "launch",
    title: "Release",
    tagline: "Protect it, ship it, promote it, get paid — the whole paperwork walkthrough, in order.",
    icon: Rocket,
    steps: [
      { key: "protect", label: "Protect", icon: Copyright, assetKind: null, href: "/copyright",
        blurb: "Register your ownership before anything goes public.",
        creditNote: "free · 100 Visual Bucs AI draft" },
      { key: "brand", label: "Brand", icon: ImageIcon, assetKind: "image", href: "/cover-art",
        blurb: "The release look — cover art that sells the drop.",
        creditNote: "200–300 Visual Bucs" },
      { key: "distribute", label: "Distribute", icon: Rocket, assetKind: null, href: "/distribute",
        blurb: "Ship your song to Spotify, Apple Music, and everywhere else.",
        creditNote: "from 100 Visual Bucs" },
      { key: "plan", label: "Release Plan", icon: ListChecks, assetKind: null, href: "/release-checklist",
        blurb: "Your AI-built week-by-week launch plan.",
        creditNote: "200 Visual Bucs" },
      { key: "promos", label: "Promos", icon: Megaphone, assetKind: "clip", href: "/promo-clip",
        blurb: "Clips, teasers, and trailers cut from your project.",
        creditNote: "from 100 Visual Bucs" },
      { key: "schedule", label: "Schedule", icon: CalendarDays, assetKind: null, href: "/scheduler",
        blurb: "Line up every post across your channels.",
        creditNote: "100 Visual Bucs/post" },
      { key: "monetize", label: "Monetize", icon: Coins, assetKind: null, href: "/coach",
        blurb: "Turn the release into revenue — pricing, sponsors, strategy.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "grow",
    family: "grow",
    title: "Audience",
    tagline: "Get seen — hooks, content, and the numbers that tell you what's working.",
    icon: TrendingUp,
    steps: [
      { key: "hooks", label: "Hooks", icon: Flame, assetKind: null, href: "/hooks",
        blurb: "Hooks that stop the scroll in the first three seconds.",
        creditNote: "100 Visual Bucs" },
      { key: "brand", label: "Brand", icon: Palette, assetKind: null, href: "/branding-kit",
        blurb: "Brand yourself — the look people remember and follow.",
        creditNote: "varies" },
      { key: "titles", label: "Titles", icon: TypeIcon, assetKind: null, href: "/titles",
        blurb: "Titles people actually click.",
        creditNote: "100 Visual Bucs" },
      { key: "collabs", label: "Collabs", icon: UserPlus, assetKind: null, href: "/collabs",
        blurb: "Find creators to collab with — grow together.",
        creditNote: "varies" },
      { key: "calendar", label: "Content Plan", icon: CalendarDays, assetKind: null, href: "/content-calendar",
        blurb: "A month of content, planned in minutes.",
        creditNote: "100 Visual Bucs" },
      { key: "virality", label: "Virality Check", icon: FlaskConical, assetKind: null, href: "/virality-check",
        blurb: "Pre-flight check before you post.",
        creditNote: "200 Visual Bucs" },
      { key: "repurpose", label: "Repurpose", icon: RefreshCw, assetKind: null, href: "/repurpose",
        blurb: "One video becomes ten — repurpose everything you make.",
        creditNote: "varies" },
      { key: "translate", label: "Translate", icon: Languages, assetKind: null, href: "/translate",
        blurb: "Take any video global — AI dubbing that keeps your voice.",
        creditNote: "500 Visual Bucs" },
      { key: "replies", label: "Replies", icon: MessageCircle, assetKind: null, href: "/comment-replies",
        blurb: "Never miss a comment — AI replies in your voice.",
        creditNote: "100 Visual Bucs" },
      { key: "contests", label: "Contests", icon: Trophy, assetKind: null, href: "/contests",
        blurb: "Run fan contests — turn viewers into an army.",
        creditNote: "varies" },
      { key: "trends", label: "Trends", icon: TrendingUp, assetKind: null, href: "/trends",
        blurb: "Ride what's blowing up right now.",
        creditNote: "200 Visual Bucs" },
      { key: "audit", label: "Channel Audit", icon: FileSearch, assetKind: null, href: "/channel-audit",
        blurb: "Audit your channel — find what's holding you back.",
        creditNote: "300 Visual Bucs" },
      { key: "analytics", label: "Analytics", icon: BarChart3, assetKind: null, href: "/analytics",
        blurb: "See what's working — then double down.",
        creditNote: "free" },
      { key: "getpaid", label: "Get Paid", icon: Coins, assetKind: null, href: "/coach",
        blurb: "The way to the money — your AI coach builds the gameplan: sponsors, pricing, revenue streams.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "influencer",
    family: "grow",
    title: "Influencer",
    tagline: "Niche → content → collabs → deals. The influencer playbook, in order.",
    icon: Users,
    steps: [
      { key: "niche", label: "Niche", icon: Lightbulb, assetKind: null, href: "/randomizer",
        blurb: "Your lane — the niche you can own.",
        creditNote: "free" },
      { key: "brand", label: "Brand", icon: ShieldCheck, assetKind: null, href: "/artist-vault",
        blurb: "Your look and voice — locked in the Creator Vault.",
        creditNote: "free" },
      { key: "content", label: "Content", icon: CalendarDays, assetKind: null, href: "/content-calendar",
        blurb: "A month of posts, planned in minutes.",
        creditNote: "100 Visual Bucs" },
      { key: "hooks", label: "Hooks", icon: Flame, assetKind: null, href: "/hooks",
        blurb: "Hooks that stop the scroll in the first three seconds.",
        creditNote: "100 Visual Bucs" },
      { key: "collabs", label: "Collabs", icon: UserPlus, assetKind: null, href: "/collabs",
        blurb: "Collab your way up — find creators in your lane.",
        creditNote: "varies" },
      { key: "deals", label: "Deals", icon: Handshake, assetKind: null, href: "/sponsors",
        blurb: "Get brands paying you to post.",
        creditNote: "500 Visual Bucs/listing" },
      { key: "analytics", label: "Analytics", icon: BarChart3, assetKind: null, href: "/analytics",
        blurb: "What's working — do more of that.",
        creditNote: "free" },
      { key: "getpaid", label: "Get Paid", icon: Coins, assetKind: null, href: "/coach",
        blurb: "The way to the money — your AI coach builds the gameplan: sponsors, pricing, revenue streams.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "ai-influencer",
    family: "grow",
    title: "AI Influencer",
    tagline: "Persona → face → voice → content → deals. Your virtual influencer, famous and paid.",
    icon: Wand2,
    steps: [
      { key: "persona", label: "Persona", icon: Lightbulb, assetKind: null, href: "/randomizer",
        blurb: "Invent them — name, niche, personality, backstory.",
        creditNote: "free" },
      { key: "brand", label: "Brand", icon: ShieldCheck, assetKind: null, href: "/artist-vault",
        blurb: "Lock their face and look — the AI never breaks character.",
        creditNote: "free" },
      { key: "voice", label: "Voice", icon: Mic2, assetKind: null, href: "/voiceover",
        blurb: "Give them a voice — locked for every video.",
        creditNote: "200 Visual Bucs" },
      { key: "photos", label: "Photos", icon: ImageIcon, assetKind: "image", href: "/cover-art",
        blurb: "Photoshoots on demand — any look, any place.",
        creditNote: "200–300 Visual Bucs" },
      { key: "videos", label: "Videos", icon: Clapperboard, assetKind: "video", href: "/make-video",
        blurb: "Video content starring your influencer.",
        creditNote: "from 400 Visual Bucs" },
      { key: "content", label: "Content", icon: CalendarDays, assetKind: null, href: "/content-calendar",
        blurb: "A month of posts, planned in minutes.",
        creditNote: "100 Visual Bucs" },
      { key: "deals", label: "Deals", icon: Handshake, assetKind: null, href: "/sponsors",
        blurb: "Get brands paying your AI influencer.",
        creditNote: "500 Visual Bucs/listing" },
      { key: "getpaid", label: "Get Paid", icon: Coins, assetKind: null, href: "/coach",
        blurb: "The way to the money — the virtual-influencer money playbook.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "clipper",
    family: "grow",
    title: "Clipper",
    tagline: "Niche → clip → post → deals. Turn other people's moments into your money.",
    icon: Scissors,
    steps: [
      { key: "niche", label: "Niche", icon: Lightbulb, assetKind: null, href: "/trends",
        blurb: "Pick your lane — gaming, podcasts, sports, drama.",
        creditNote: "free" },
      { key: "brand", label: "Brand", icon: Palette, assetKind: null, href: "/branding-kit",
        blurb: "Your clipping brand — watermark and style people recognize.",
        creditNote: "varies" },
      { key: "clip", label: "Clip", icon: Scissors, assetKind: "clip", href: "/clip-maker",
        blurb: "Cut the moments — AI finds the highlights, you pick the killers.",
        creditNote: "from 100 Visual Bucs" },
      { key: "hooks", label: "Hooks", icon: Flame, assetKind: null, href: "/hooks",
        blurb: "Hooks and captions that make clips travel.",
        creditNote: "100 Visual Bucs" },
      { key: "post", label: "Post", icon: CalendarDays, assetKind: null, href: "/content-calendar",
        blurb: "Volume wins — plan a week of clips in one sitting.",
        creditNote: "100 Visual Bucs" },
      { key: "deals", label: "Deals", icon: Handshake, assetKind: null, href: "/brand-deals",
        blurb: "Rev-share deals with the streamers you clip.",
        creditNote: "200 Visual Bucs/search" },
      { key: "getpaid", label: "Get Paid", icon: Coins, assetKind: null, href: "/coach",
        blurb: "The way to the money — the clipper money playbook.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "monetize",
    family: "monetize",
    title: "Money",
    tagline: "Get paid — sponsors, deals, royalties, merch, and your own shop.",
    icon: Coins,
    steps: [
      { key: "strategy", label: "Strategy", icon: Coins, assetKind: null, href: "/coach",
        blurb: "Your money gameplan, built around your content.",
        creditNote: "100 Visual Bucs" },
      { key: "outreach", label: "Outreach", icon: Send, assetKind: null, href: "/sponsorship-outreach",
        blurb: "Pitch brands that fit — outreach done for you.",
        creditNote: "varies" },
      { key: "sponsors", label: "Sponsors", icon: Handshake, assetKind: null, href: "/sponsors",
        blurb: "Get brands paying you to create.",
        creditNote: "500 Visual Bucs/listing" },
      { key: "deals", label: "Brand Deals", icon: Briefcase, assetKind: null, href: "/brand-deals",
        blurb: "Find and pitch brand deals that fit your niche.",
        creditNote: "200 Visual Bucs/search" },
      { key: "calculator", label: "Worth", icon: Calculator, assetKind: null, href: "/brand-calculator",
        blurb: "Know your worth — price every deal right.",
        creditNote: "200 Visual Bucs" },
      { key: "shows", label: "Shows", icon: Ticket, assetKind: null, href: "/shows",
        blurb: "Book shows — get paid to perform.",
        creditNote: "100 Visual Bucs" },
      { key: "royalties", label: "Royalties", icon: Banknote, assetKind: null, href: "/royalties",
        blurb: "Track every dollar your music earns.",
        creditNote: "100 Visual Bucs" },
      { key: "tips", label: "Tips", icon: DollarSign, assetKind: null, href: "/tips",
        blurb: "Tip jar — let fans pay you directly.",
        creditNote: "varies" },
      { key: "shoutouts", label: "Shoutouts", icon: Megaphone, assetKind: null, href: "/shoutouts",
        blurb: "Sell shoutouts to your fans.",
        creditNote: "100 Visual Bucs" },
      { key: "merch", label: "Merch", icon: Shirt, assetKind: null, href: "/merch",
        blurb: "Merch designed by AI, sold by you.",
        creditNote: "300 Visual Bucs/batch" },
      { key: "brandingshop", label: "Branding Shop", icon: ShoppingBag, assetKind: null, href: "/branding-shop",
        blurb: "AI-designed branding products, dropshipped for you.",
        creditNote: "varies" },
      { key: "luxury", label: "Luxury", icon: Gem, assetKind: null, href: "/jewelry",
        blurb: "Your logo, reimagined as luxury jewelry.",
        creditNote: "from 100 Visual Bucs" },
      { key: "liveshopping", label: "Live Selling", icon: ShoppingCart, assetKind: null, href: "/live-shopping",
        blurb: "Sell live — turn streams into shopping events.",
        creditNote: "100 Visual Bucs" },
      { key: "shop", label: "My Shop", icon: Store, assetKind: null, href: "/my-shop",
        blurb: "Your own storefront on your own terms.",
        creditNote: "100 Visual Bucs" },
    ],
  },
  {
    type: "learn",
    family: "learn",
    title: "Knowledge",
    tagline: "Level up — courses, playbooks, and the legal basics every creator needs.",
    icon: GraduationCap,
    steps: [
      { key: "academy", label: "Academy", icon: GraduationCap, assetKind: null, href: "/academy",
        blurb: "Courses that level you up as a creator.",
        creditNote: "100 Visual Bucs" },
      { key: "guides", label: "Guides", icon: BookOpen, assetKind: null, href: "/guides",
        blurb: "Playbooks for every platform.",
        creditNote: "free" },
      { key: "llc", label: "LLC Setup", icon: Scale, assetKind: null, href: "/llc-guide",
        blurb: "Set up your business the right way.",
        creditNote: "free" },
      { key: "copyright", label: "Copyright", icon: Copyright, assetKind: null, href: "/copyright",
        blurb: "Own your work, legally — from day one.",
        creditNote: "free · 100 Visual Bucs AI draft" },
      { key: "detector", label: "AI Detector", icon: ScanSearch, assetKind: null, href: "/detector",
        blurb: "Spot AI-generated media — know what's real.",
        creditNote: "200 Visual Bucs" },
    ],
  },
  {
    type: "business",
    family: "business",
    title: "Paperwork",
    tagline: "Handle the paperwork — LLC, contracts, press kit, and your audience list.",
    icon: Briefcase,
    steps: [
      { key: "llc", label: "LLC", icon: Scale, assetKind: null, href: "/llc-guide",
        blurb: "Form your LLC the right way, step by step.",
        creditNote: "free" },
      { key: "contracts", label: "Contracts", icon: FileText, assetKind: null, href: "/contracts",
        blurb: "Contracts that protect you on every deal.",
        creditNote: "300 Visual Bucs" },
      { key: "presskit", label: "Press Kit", icon: Newspaper, assetKind: null, href: "/press-kit",
        blurb: "Look legit to press, brands, and bookers.",
        creditNote: "300 Visual Bucs" },
      { key: "interview", label: "Interviews", icon: Presentation, assetKind: null, href: "/interview-prep",
        blurb: "Nail every interview and press appearance.",
        creditNote: "200 Visual Bucs" },
      { key: "emaillist", label: "Email List", icon: Mail, assetKind: null, href: "/email-list",
        blurb: "Own your audience — no algorithm required.",
        creditNote: "100 Visual Bucs" },
    ],
  },
];

export function getWorkflow(type: HubProjectType): ProjectWorkflow {
  return PROJECT_WORKFLOWS.find((w) => w.type === type) ?? PROJECT_WORKFLOWS[0]!;
}

/* ─── Shared asset language ─────────────────────────────────────────────── */

export const KIND_LABEL: Record<HubAssetKind, string> = {
  beat: "Beat", stems: "Stems", song: "Song", video: "Video",
  clip: "Clip", thumbnail: "Thumbnail", image: "Image", script: "Script", sfx: "SFX", other: "Asset",
};

export const AUDIO_KINDS: HubAssetKind[] = ["beat", "song", "stems", "clip", "sfx"];

/* Where each finished asset naturally wants to go next. */
export const NEXT_STEPS: Record<HubAssetKind, { label: string; href: string }[]> = {
  beat: [
    { label: "Split into stems", href: "/stems" },
    { label: "Make it a song", href: "/make-song" },
  ],
  stems: [{ label: "Make it a song", href: "/make-song" }],
  song: [
    { label: "Make the video", href: "/make-video" },
    { label: "Cut a promo clip", href: "/promo-clip" },
    { label: "Plan the release", href: "/release-checklist" },
  ],
  video: [
    { label: "Edit the final cut", href: "/video-editor" },
    { label: "Cut a promo clip", href: "/promo-clip" },
    { label: "Make a thumbnail", href: "/thumbnail-maker" },
    { label: "Plan the release", href: "/release-checklist" },
  ],
  clip: [
    { label: "Make a thumbnail", href: "/thumbnail-maker" },
    { label: "Post it", href: "/promo-clip" },
  ],
  thumbnail: [
    { label: "A/B test it", href: "/thumbnail-test" },
    { label: "Cut a promo clip", href: "/promo-clip" },
  ],
  image: [
    { label: "Make the video", href: "/make-video" },
    { label: "Make a thumbnail", href: "/thumbnail-maker" },
  ],
  script: [{ label: "Voice it", href: "/voiceover" }],
  sfx: [{ label: "Add character voices", href: "/voiceover" }],
  other: [],
};
